[workspace]
resolver = "2"
members = [
  "crates/neurite-app",
  "crates/neurite-control",
  "crates/neurite-core",
  "crates/neurite-scene",
  "crates/neurite-events",
  "crates/neurite-protocol",
  "crates/neurite-workspace",
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.lints.rust]
unsafe_code = "forbid"
